# Generated by Django 5.1.1 on 2024-10-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=15)),
                ('idade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data_nascimento', models.DateField()),
                ('raça', models.CharField(max_length=15)),
                ('cor', models.CharField(max_length=15)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
