# Generated by Django 5.1.1 on 2024-10-16 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='raça',
            new_name='raca',
        ),
    ]
