# Generated by Django 5.1.1 on 2024-10-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_rename_raça_pet_raca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='data_nascimento',
            field=models.CharField(max_length=10),
        ),
    ]
