# Generated by Django 5.1.1 on 2024-10-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_alter_pet_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='data_nascimento',
            field=models.DateField(),
        ),
    ]
